# Generated by Django 4.2.7 on 2023-11-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=50, verbose_name='药品名称')),
                ('sup_id', models.IntegerField(max_length=20, verbose_name='供应商编号')),
                ('productor_id', models.CharField(max_length=100, verbose_name='生产批号')),
                ('productor_place', models.CharField(max_length=50, verbose_name='产地')),
                ('type', models.CharField(max_length=50, verbose_name='所属类别')),
                ('in_price', models.FloatField(max_length=10, verbose_name='进价')),
                ('single_price', models.FloatField(max_length=10, verbose_name='单价')),
                ('discount', models.FloatField(max_length=3, verbose_name='会员折扣')),
                ('package', models.IntegerField(max_length=20, verbose_name='库存')),
                ('size', models.CharField(max_length=50, verbose_name='规格')),
                ('pro_date', models.CharField(max_length=50, verbose_name='生产日期')),
                ('valid_date', models.CharField(max_length=50, verbose_name='有效期')),
            ],
        ),
        migrations.CreateModel(
            name='in_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.CharField(max_length=500, verbose_name='入库v号')),
            ],
        ),
        migrations.CreateModel(
            name='in_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('io_number', models.IntegerField(max_length=500, verbose_name='收支编号')),
                ('drug_id', models.IntegerField(max_length=500, verbose_name='药品')),
                ('worker_id', models.IntegerField(max_length=500, verbose_name='员工编号')),
                ('number', models.IntegerField(max_length=500, verbose_name='数量')),
                ('date', models.IntegerField(max_length=50, verbose_name='日期')),
                ('money', models.FloatField(max_length=10, verbose_name='总额')),
                ('type', models.CharField(max_length=50, verbose_name='类别')),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_increment', models.CharField(max_length=500, verbose_name='经理编号')),
                ('user_increment', models.CharField(max_length=500, verbose_name='用户编号')),
            ],
        ),
        migrations.CreateModel(
            name='memeber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.CharField(max_length=16, verbose_name='客户编号')),
                ('name', models.IntegerField(verbose_name='姓名')),
                ('email', models.CharField(max_length=32, verbose_name='联系方式')),
            ],
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50, verbose_name='供应商名称')),
                ('linkman', models.CharField(max_length=50, verbose_name='联系人')),
                ('linkway', models.CharField(max_length=50, verbose_name='联系方式')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_increment', models.CharField(max_length=500, verbose_name='用户编号')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=50, verbose_name='密码')),
                ('type', models.CharField(max_length=50, verbose_name='类别')),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField(max_length=500, verbose_name='员工编号')),
                ('worker_name', models.CharField(max_length=50, verbose_name='员工姓名')),
                ('telephone', models.CharField(max_length=500, verbose_name='联系电话')),
                ('user_increment', models.CharField(max_length=500, verbose_name='用户编号')),
            ],
        ),
    ]
