# Generated by Django 4.2.7 on 2023-11-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.CharField(max_length=16, verbose_name='客户编号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系方式')),
            ],
        ),
        migrations.DeleteModel(
            name='memeber',
        ),
    ]
