# Generated by Django 4.2.7 on 2023-11-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_member_delete_memeber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='package',
            field=models.IntegerField(verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='sup_id',
            field=models.IntegerField(verbose_name='供应商编号'),
        ),
        migrations.AlterField(
            model_name='in_document',
            name='in_id',
            field=models.CharField(max_length=500, verbose_name='入库号'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.IntegerField(verbose_name='员工编号'),
        ),
    ]
