# Generated by Django 4.2.7 on 2023-11-27 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_drugs_package_alter_drugs_sup_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugs',
            old_name='productor_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='drugs',
            old_name='productor_place',
            new_name='product_place',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='linkway',
            new_name='linkWay',
        ),
        migrations.RemoveField(
            model_name='in_out',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='in_document',
            name='io_number',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.CASCADE, to='demo.in_out', verbose_name='关联收支编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='in_document',
            name='provider_id',
            field=models.ForeignKey(default=2345100, on_delete=django.db.models.deletion.CASCADE, to='demo.provider', verbose_name='管理供应商ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='in_out',
            name='user_increment',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.CASCADE, to='demo.user', verbose_name='关联用户编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_id',
            field=models.IntegerField(default=100000, verbose_name='供应商编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drugs',
            name='sup_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.user', verbose_name='关联供应商'),
        ),
        migrations.AlterField(
            model_name='in_document',
            name='in_id',
            field=models.CharField(max_length=50, verbose_name='入库号'),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='drug_id',
            field=models.IntegerField(max_length=50, verbose_name='药品'),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='io_number',
            field=models.IntegerField(default=1000000, max_length=50, verbose_name='收支编号'),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='number',
            field=models.IntegerField(max_length=50, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user_increment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.user', verbose_name='关联用户编号'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user_increment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.user', verbose_name='关联用户编号'),
        ),
        migrations.CreateModel(
            name='sell_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sell', models.IntegerField(verbose_name='销售编号')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.member', verbose_name='关联客户编号')),
                ('io_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.in_out', verbose_name='关联收支编号')),
            ],
        ),
        migrations.CreateModel(
            name='sales_returning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_returning', models.IntegerField(verbose_name='退货编号')),
                ('id_sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.sell_manage', verbose_name='关联销售编号')),
                ('io_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.in_out', verbose_name='关联收支编号')),
            ],
        ),
    ]
