# Generated by Django 4.2.7 on 2023-11-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_rename_productor_id_drugs_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugs',
            name='sup_id',
        ),
        migrations.AlterField(
            model_name='in_out',
            name='date',
            field=models.IntegerField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='drug_id',
            field=models.IntegerField(verbose_name='药品'),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='io_number',
            field=models.IntegerField(verbose_name='收支编号'),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='number',
            field=models.IntegerField(verbose_name='数量'),
        ),
    ]
