# Generated by Django 4.2.7 on 2023-11-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_remove_drugs_sup_id_alter_in_out_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_out',
            name='user_increment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.user', verbose_name='关联用户编号'),
        ),
    ]
