# Generated by Django 4.2.7 on 2023-11-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_alter_in_out_user_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_out',
            name='user_increment',
            field=models.IntegerField(default=100012, verbose_name='关联员工编号'),
            preserve_default=False,
        ),
    ]
