# Generated by Django 4.2.7 on 2023-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_alter_in_out_user_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='pro_date',
            field=models.DateField(verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='valid_date',
            field=models.DateField(verbose_name='有效期'),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='date',
            field=models.DateTimeField(verbose_name='日期'),
        ),
    ]
