# Generated by Django 4.2.7 on 2023-12-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_alter_drugs_pro_date_alter_drugs_valid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_document',
            name='io_number',
            field=models.IntegerField(verbose_name='关联收支编号'),
        ),
        migrations.AlterField(
            model_name='in_document',
            name='provider_id',
            field=models.IntegerField(verbose_name='关联供应商ID'),
        ),
    ]
