# Generated by Django 4.2.7 on 2023-12-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_alter_in_document_io_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_document',
            name='number',
            field=models.IntegerField(default=1, verbose_name='进货数量'),
            preserve_default=False,
        ),
    ]
