# Generated by Django 4.2.7 on 2023-12-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_in_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_returning',
            name='number',
            field=models.IntegerField(default=1, verbose_name='退货数量'),
            preserve_default=False,
        ),
    ]
