# Generated by Django 4.2.7 on 2023-12-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_sales_returning_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=5000, verbose_name='您的余额'),
            preserve_default=False,
        ),
    ]
