# Generated by Django 4.2.7 on 2023-12-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_document',
            name='name',
            field=models.CharField(default=100001, max_length=50, verbose_name='药品名称'),
            preserve_default=False,
        ),
    ]
